### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by jaanos** [metodj/APPR#1]
Svetujem, da v repozitorij dodaš datoteko `.gitignore`, da lahko določiš, katere datoteke ne gredo v repozitorij. Trenutno imaš na repozitoriju mapo `.ipynb_checkpoints`, ki pa tja ne spada, saj gre za zgodovino tvojih delovnih zvezkov - v ta namen imaš že git. Najbolje bo torej, da kar skopiraš datoteko [`.gitignore`](https://github.com/jaanos/APPR-2017/blob/master/.gitignore) iz vzorca in vanjo dodaš še vrstico
```
.ipynb_checkpoints
```
Mapo s tem imenom tudi pobriši iz repozitorija - če jo želiš pri sebi ohraniti, jo začasno premakni nekam drugam, potem naredi commit, da se zabeleži njen izbris, potem pa jo lahko vrneš (zaradi vnosa v `.gitignore` ti je potem git več ne bo ponujal za nadaljnje commite).

**Comment by metodj** [comment]
Sem popravil, hvala za komentar.
