### ISSUE TITLE
Zanka for in uvoz

### ISSUE THREAD

**Issue by jaanos** [metodj/APPR#2]
Opažam, da v `Delnice_binarni_klasifikator.ipynb` na več mestih uporabljaš zanko `for`. Ta je primerna, ko večkrat izvajaš isti ukaz ali zaporedje ukazov (npr. tvoj uvoz podatkov iz spletne strani), izogibaj pa se je, če samo gradiš vektor. Večina R-jevih funkcij namreč deluje na vektorjih. Če npr. uporabljaš `gsub`, enostavno podaj vektor nizov, pa bo rezultat vektor nizov z opravljenimi spremembami. Če hočeš vektor nizov stakniti v en sam niz, uporabi `paste` s parametrom `collapse`.

Dodajanje, brisanje in spreminjanje stolpcev je morda najlažje s funkcijami `select` (izbira oziroma opuščanje obstoječih stolpcev), `rename` (preimenovanje navedenih stolpcev), `mutate` (dodajanje novih stolpcev) in `transmute` (zamenjava stolpcev z navedenimi) iz knjižnice `dplyr`. Obenem lahko poskrbiš tudi za pretvorbo tipov, ki je najbolj enostavna s funkcijami `parse_*` iz knjižnice `readr`. Po branju iz spletne strani lahko torej tabelo urediš tako:
```R
en <- locale("en", date_format = "%b %d, %Y", decimal_mark = ".", grouping_mark = ",")
tabela <- tabela %>% transmute(Date = parse_date(Date, locale = en),
                               Open = parse_number(Open, locale = en),
                               Close = parse_number(Close, locale = en)) %>%
    mutate(Gibanje = ifelse(Open < Close, 1, 0))
```
Stolpcec `Gibanje` je v resnici izpeljan, tako da ga v obliki *tidy data* ne bi smelo biti - izpelješ ga takrat, ko ga potrebuješ. Funkcija `ifelse` sprejme tri vektorje (po potrebi ciklično dopolnjene do) iste dolžine in vrne vektor, ki je na mestih, kjer je prvi vektor `TRUE`, enak drugemu vektorju, sicer pa tretjemu vektorju. Ko računaš delež, lahko tako stolpec `Gibanje` sproti izračunaš:
```R
tabela %>% transmute(Gibanje = ifelse(Open < Close, 1, 0)) %>% .$Gibanje %>% mean() %>% round(2)
```
Seveda ga je smiselno imeti poračunanega, če ga boš še kje potreboval.

Stolpec `Date` je tipa datum - `ggplot2` zna delati tudi s takimi podatki. Graf lahko zdaj enostavno narišeš tako:
```R
ggplot(data = tabela, mapping = aes(x = Date, y = Close)) + 
  geom_point(size=0.75) + geom_smooth() + labs(x = "Date", y = "Dow Jones Index value ($)")
```

Pri uvozu novic uporabi funkcijo `read_csv` iz knjižnice `readr` - tako lahko določiš, da bo stolpec `Date` istega tipa kot istoimenski stolpec v razpredelnici `tabela`:
```R
D2 <- read_csv("files/RedditNews.csv", col_types = cols(Date = col_date()))
```
Tako tudi ne bo potrebno pretvarjati datumov, saj so že v isti obliki.

Namesto `aggregate` raje uporabi funkciji `group_by` in `summarise` iz knjižnice `dplyr`, npr.
```R
news <- D2 %>% group_by(Date) %>% summarise(News = paste(News, collapse = " "))
```
Tako ti tudi pravilno stakne nize skupaj. Nizi, ki se začnejo z `b'` ali `b"`, so že v datoteki `RedditNews.csv` - to popravi že pred združevanjem. Raje kot `merge` uporabi `inner_join` iz knjižnice `dplyr`:
```R
test <- inner_join(tabela, news, by = "Date")
```

V `Credit_model.ipynb` uvoziš datoteko `loan.csv`, a te nimaš na repozitoriju. Tako kot prej svetujem, da raje za uvoz uporabiš `read_csv` (s podčrtajem namesto s piko).

**Comment by metodj** [comment]
Hvala za komentar in vse koristne nasvete! Na for zanko sem navajen iz Pythona in sem zato na tak način gradil nove vektorje. Tudi nisem vedel, da je pretvorba ("parse") tipov tako enostavna  s knjižnico readr. Zaenkrat bom uvoz pustil v taki obliki, saj sta oba "notebooka" delovni verziji mojega projekta. V končni verziji bom nato seveda uporabil vaše izboljšave.

Stolpec "Gibanje" bom vseeno pustil v tabeli, saj je v njem zajeta ključna informacija, ki jo bom kasneje v prediktivnem modelu poskušal napovedati.

Datoteka loan.csv je velika 110MB in mi je git ni pustil uvoziti na repozitorij, ker gre za prevelik fajl. Jaz jo imam na svojem računalniku, na repozitoriju pa jo sedaj tako ali tako ne potrebujem, ker bom naprej vse delal z "downsample" verzijo teh podatkov.

**Comment by jaanos** [comment]
Aha, vidim, da imaš napisano glede `loan.csv`.

Svetoval bi še, da imaš v `README.md` nekakšno "kazalo", da bo jasno videti, v kakšnem logičnem zaporedju si sledijo tvoji delovni zvezki (ki so hkrati tudi poročilo za tvoj projekt).

Tole zadevo bom pustil odprto - zapri, ko se ti zdi primerno.
