### ISSUE TITLE
Prikaz podatkov na zemljevidu

### ISSUE THREAD

**Issue by metodj** [metodj/APPR#3]
Na zemljevidu v Credit_model.ipybn bi rad predstavil, dva podatka hkrati. S stopnjo barve (parameter fill) bi rad predstavili velikost dolga v zvezni državi, z barvo (parameter colour) pa razred povprečne plače gospodinjstev. Če uporabim oba parametra hkrati, dobim "neuporaben" zemljevid, saj mi obarva le meje oz. robove zveznih držav. Zanima me, kako bi na najboljši način prikazal oba podatka hkrati na enem grafu? Zanima me še, če bi lahko tudi izpisal okrajšave za imena zveznih državah na zemljevidu? Da bi npr. na območju Floride pisalo FL.

**Comment by jaanos** [comment]
Najprej poskrbi, da si ukazi v delovnem zvezku sledijo tako, da jih bo mogoče uporabiti - glede na to, da imaš downsample v datoteki CSV, pred njihovo uporabo poskrbi še za njihov uvoz.

Za združevanje podatkov po znakovnih spremenljivkah je najbolje, če delaš s faktorjema z istimi vrednostmi. Za to lahko poskrbiš že pri pripravi podatkov. Da v zemljevidu na bo lukenj, namesto `inner_join` raje uporabi `left_join`:
```R
skupaj <- downsampl %>% transmute(addr_state = factor(addr_state, levels = levels(zda$STUSPS)),
                                  loan_amnt, annual_inc) %>% 
    group_by(addr_state) %>% summarise(dolg = sum(loan_amnt), povpr_dohodek = mean(annual_inc))

tmp <- left_join(zda, skupaj, by = c("STUSPS" = "addr_state"))
```

Za prikaz dveh podatkov na zemljevidu lahko poleg barve vsakega območja narišeš še točke, katerih velikost je določena s prikazano vrednostjo. Točke lahko narišeš npr. v povprečje koordinat za vsako območje - to bo približno ustrezalo središču vsake zvezne države. Iste koordinate lahko uporabiš tudi za izris tekstovnih oznak, npr.
```R
ggplot(data = tmp %>% group_by(STUSPS, razred_plac) %>% summarise(x = mean(long), y = mean(lat))) +
  geom_polygon(data = tmp, aes(x = long, y = lat, group = group, fill = dolg)) +
  geom_point(aes(x = x, y = y, size = razred_plac), color = "red") +
  geom_text(aes(x = x, y = y, label = STUSPS), size = 2) +
  coord_map(xlim = c(-125, -65), ylim = c(25, 50))
```
`ggplot2` te sicer opozori, da uporaba kategoričnih spremenljivk s parametrom `size` ni najboljša ideja - v tvojem primeru so sicer kategorije pravilno razporejene, tako da se izide v redu (lahko bi sicer poskrbel, da imaš urejen faktor, a bi se opozorilo še vedno izpisalo). Lahko bi sicer namesto `razred_plac` uporabil kar `povpr_dohodek`, a se mi zdi, da je potem težko razlikovati med velikostmi pik.

Še to: na vzhodu je veliko majhnih držav, zaradi česar pride do prekrivanja (in je že njihove barve težko videti). Razmisli, če bi morda ta del prikazal v posebnem zemljevidu.
