### ISSUE TITLE
Predstavitev

### ISSUE THREAD

**Issue by jaanos** [metodj/APPR#4]
Glede na to, da delaš v Jupyter notebooku, me zanima, kako bi predstavil svoj projekt - ali boš samo pokazal delovne zvezke na GitHubu, ali bi rad sproti kaj poganjal v Jupyter notebooku? Če želiš, lahko predstavitev opraviš tudi iz svojega računalnika. Vidim, da imaš tudi že objavljeno Shiny aplikacijo.

Ko boš imel pripravljeno različico projekta za predstavitev, odpri issue na [repozitoriju za zagovore](https://github.com/jaanos/APPR-2017-zagovori), da dodam povezavo - tam si preberi natančnejša navodila.

**Comment by metodj** [comment]
Za predstavitev bom samo pokazal delovne zvezke na Githubu, saj ne potrebujem ničesar pognati iz Jupyter notebooka. Shiny aplikacijo pa sem objavil prek shiny serverja in je dostopna na spletnem naslovu, ki sem ga objavil v notebooku.

**Comment by jaanos** [comment]
V redu, velja. Potem samo javi, ko boš imel pripravljeno različico za predstavitev, kot sem napisal zgoraj. Če se ti zdi primerno, lahko to zadevo zapreš.

**Comment by metodj** [comment]
Zaenkrat je to to, tako da bom dodal povezavo na repozitorij za zagovore. Kasneje bom še v juniju dodal nove stvari.
